"""Criando tabelas iniciais

Revision ID: b391d4feeed4
Revises: 
Create Date: 2025-03-30 23:48:32.504428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b391d4feeed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_inicial', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projeto_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projeto_nome'), ['nome'], unique=True)

    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_inicial', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atividade_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atividade_id'))

    op.drop_table('atividade')
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projeto_nome'))
        batch_op.drop_index(batch_op.f('ix_projeto_id'))

    op.drop_table('projeto')
    # ### end Alembic commands ###
